version=0.5.7
asCommonsVersion=0.3.2
# Update version in buildSrc/build.gradle.kts as well
docx4jVersion=11.5.13
slf4jApiVersion=2.0.18
logbackClassicVersion=1.5.32
guiceVersion=7.0.0
testngVersion=7.12.0
moxyVersion=6.0.0
eclipseMoxyVersion=5.0.0
reportngVersion=1.1.4
commonsCodecVersion=1.22.0
batikVersion=1.19
guavaVersion=33.6.0-jre
