/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
    val catalogFile = file("gradle/libs.versions.toml")
    val pluginVersion =
        catalogFile
            .readText()
            .lines()
            .firstNotNullOfOrNull { line ->
                Regex("""^semver-release-plugin\s*=\s*\"([^\"]+)\"""")
                    .matchEntire(line.trim())
                    ?.groupValues
                    ?.get(1)
            }
            ?: error("semver-release-plugin version not found in ${catalogFile.absolutePath}")
    plugins {
        id("io.github.sfali23.gradle-semantic-versioning-release") version pluginVersion
    }
}

plugins {
    id("io.github.sfali23.gradle-semantic-versioning-release")
}

semverrelease {
    addUnReleasedCommitsToTagComment.set(true)
}

include(":app")
project(":app").name = "docx4j-builder"
