/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id("io.github.sfali23.gradle-semantic-versioning-release") version "0.4.0"
    }
}

plugins {
    id("io.github.sfali23.gradle-semantic-versioning-release")
}

semverrelease {
    addUnReleasedCommitsToTagComment.set(true)
}

include(":app")
project(":app").name = "docx4j-builder"
